import fs from 'fs';
const data = [
  {
    packetsAvailable: 19,
    size: 0,
    name: 'Golden Ganesh',
    weightPerUnit: 1000,
    totalWeight: 19000,
    category: 'ganesh',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'FALSE',
  },
  {
    packetsAvailable: 60,
    size: 6,
    name: 'Red stone',
    weightPerUnit: 500,
    totalWeight: 30000,
    category: 'stone',
    unit: 'mm',
    color: 'red',
    hasWeight: 'FALSE',
  },
  {
    packetsAvailable: 4,
    size: 3,
    name: 'Golden chakri',
    weightPerUnit: 500,
    totalWeight: 2000,
    category: 'stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'FALSE',
  },
  {
    packetsAvailable: 2,
    size: 6,
    name: 'Golden chakri',
    weightPerUnit: 1000,
    totalWeight: 2000,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 22,
    size: 5,
    name: 'Golden chakri',
    weightPerUnit: 500,
    totalWeight: 11000,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 1,
    size: 8,
    name: 'Blue stamping stone',
    weightPerUnit: 600,
    totalWeight: 600,
    category: 'stamping,stone',
    unit: 'mm',
    color: 'blue',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 4,
    size: 4,
    name: 'Green paan',
    weightPerUnit: 500,
    totalWeight: 2000,
    category: 'paan,stone',
    unit: 'mm',
    color: 'green',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 3,
    size: 4,
    name: 'White Markis',
    weightPerUnit: 500,
    totalWeight: 1500,
    category: 'markis,stone',
    unit: 'mm',
    color: 'white',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 2,
    size: 3,
    name: 'Morpich Markis',
    weightPerUnit: 500,
    totalWeight: 1000,
    category: 'markis,stone',
    unit: 'mm',
    color: 'morpich',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 1,
    size: 6,
    name: 'Golden taklu',
    weightPerUnit: 500,
    totalWeight: 500,
    category: 'taklu,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'FALSE',
  },
  {
    packetsAvailable: 2,
    size: 8,
    name: 'Golden taklu',
    weightPerUnit: 1000,
    totalWeight: 2000,
    category: 'taklu,golden',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 9,
    size: 3,
    name: 'Green stamping',
    weightPerUnit: 500,
    totalWeight: 4500,
    category: 'stamping,stone',
    unit: 'mm',
    color: 'green',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 11,
    size: 10,
    name: 'Red flower',
    weightPerUnit: 500,
    totalWeight: 5500,
    category: 'flower,stone',
    unit: 'mm',
    color: 'red',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 10,
    name: 'Green flower',
    weightPerUnit: 500,
    totalWeight: 2500,
    category: 'flower,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 1,
    size: 4,
    name: 'Green paan',
    weightPerUnit: 600,
    totalWeight: 600,
    category: 'paan,stone',
    unit: 'mm',
    color: 'green',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 2,
    size: 3,
    name: 'Golden paan',
    weightPerUnit: 1000,
    totalWeight: 2000,
    category: 'paan,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 3,
    name: 'Golden teen tikki',
    weightPerUnit: 1000,
    totalWeight: 5000,
    category: 'tikki,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 11,
    size: 4,
    name: 'Green stamping',
    weightPerUnit: 500,
    totalWeight: 5500,
    category: 'stamping,stone',
    unit: 'mm',
    color: 'green',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 4,
    name: 'Golden stone',
    weightPerUnit: 1000,
    totalWeight: 5000,
    category: 'sone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 2,
    size: 4,
    name: 'Morpich stone',
    weightPerUnit: 1000,
    totalWeight: 2000,
    category: 'sone',
    unit: 'mm',
    color: 'morpich',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 2,
    size: 3,
    name: 'Golden chakri new',
    weightPerUnit: 500,
    totalWeight: 1000,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 3,
    size: 3,
    name: 'Golden stone',
    weightPerUnit: 500,
    totalWeight: 1500,
    category: 'stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 4,
    size: 6,
    name: 'Golden mor',
    weightPerUnit: 500,
    totalWeight: 2000,
    category: 'mor,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 20,
    size: 4,
    name: 'Green stamping',
    weightPerUnit: 500,
    totalWeight: 10000,
    category: 'stamping,stone',
    unit: 'mm',
    color: 'green',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 20,
    size: 5,
    name: 'Green stamping',
    weightPerUnit: 500,
    totalWeight: 10000,
    category: 'stamping,stone',
    unit: 'mm',
    color: 'green',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 5,
    name: 'taklu',
    weightPerUnit: 500,
    totalWeight: 2500,
    category: 'taklu,golden',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 4,
    size: 4,
    name: 'Silver chakri',
    weightPerUnit: 1000,
    totalWeight: 4000,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'silver',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 4,
    size: 4,
    name: 'Moti',
    weightPerUnit: 500,
    totalWeight: 2000,
    category: 'moti,stone',
    unit: 'mm',
    color: 'white',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 60,
    size: 6,
    name: 'Green stone',
    weightPerUnit: 500,
    totalWeight: 30000,
    category: 'stone',
    unit: 'mm',
    color: 'green',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 8,
    name: 'Golden acrylic paan',
    weightPerUnit: 500,
    totalWeight: 2500,
    category: 'acrylic,paan,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 6,
    size: 6,
    name: 'taklu',
    weightPerUnit: 500,
    totalWeight: 3000,
    category: 'taklu',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 22,
    size: 4,
    name: 'Red stone',
    weightPerUnit: 500,
    totalWeight: 11000,
    category: 'stone',
    unit: 'mm',
    color: 'red',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 9,
    size: 3,
    name: 'Red stone',
    weightPerUnit: 500,
    totalWeight: 4500,
    category: 'stone',
    unit: 'mm',
    color: 'red',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 1,
    size: 5,
    name: 'White stone',
    weightPerUnit: 1000,
    totalWeight: 1000,
    category: 'stone',
    unit: 'mm',
    color: 'white',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 1,
    size: 5,
    name: 'Keri wala paan',
    weightPerUnit: 1000,
    totalWeight: 1000,
    category: 'keri,paan,stone',
    unit: 'mm',
    color: 'none',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 1,
    size: 3,
    name: 'Golden chakri',
    weightPerUnit: 1000,
    totalWeight: 1000,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 60,
    size: 10,
    name: 'Golden red',
    weightPerUnit: 500,
    totalWeight: 30000,
    category: 'stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 60,
    size: 4,
    name: 'White stone',
    weightPerUnit: 500,
    totalWeight: 30000,
    category: 'stone',
    unit: 'mm',
    color: 'white',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 3,
    size: 5,
    name: 'Moti white',
    weightPerUnit: 500,
    totalWeight: 1500,
    category: 'moti,stone',
    unit: 'mm',
    color: 'white',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 3,
    size: 5,
    name: 'Karthi',
    weightPerUnit: 1000,
    totalWeight: 3000,
    category: 'karthi,stone',
    unit: 'mm',
    color: 'none',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 4,
    name: 'taklu',
    weightPerUnit: 500,
    totalWeight: 2500,
    category: 'taklu,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 8,
    size: 3,
    name: 'Green stone',
    weightPerUnit: 500,
    totalWeight: 4000,
    category: 'stone',
    unit: 'mm',
    color: 'green',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 30,
    size: 3,
    name: 'Moti',
    weightPerUnit: 500,
    totalWeight: 15000,
    category: 'moti,stone',
    unit: 'mm',
    color: 'white',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 3,
    name: 'Rose new',
    weightPerUnit: 500,
    totalWeight: 2500,
    category: 'stone',
    unit: 'mm',
    color: 'rose',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 6,
    name: 'Golden chakri old',
    weightPerUnit: 500,
    totalWeight: 2500,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 2,
    size: 3,
    name: 'Blue stone',
    weightPerUnit: 500,
    totalWeight: 1000,
    category: 'stone',
    unit: 'mm',
    color: 'blue',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 30,
    size: 5,
    name: 'White Markis',
    weightPerUnit: 500,
    totalWeight: 15000,
    category: 'markis,stone',
    unit: 'mm',
    color: 'white',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 2,
    size: 4,
    name: 'Golden chakri',
    weightPerUnit: 100,
    totalWeight: 200,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 5,
    size: 3,
    name: 'Golden chakri old',
    weightPerUnit: 100,
    totalWeight: 500,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 10,
    size: 3,
    name: 'Golden acrylic paan',
    weightPerUnit: 500,
    totalWeight: 5000,
    category: 'acrylic,paan,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 1,
    size: 5,
    name: 'Rose golden chakri',
    weightPerUnit: 1000,
    totalWeight: 1000,
    category: 'chakri,stone',
    unit: 'mm',
    color: 'rose golden',
    hasWeight: 'TRUE',
  },
  {
    packetsAvailable: 1,
    size: 5,
    name: 'Golden paan checks',
    weightPerUnit: 1000,
    totalWeight: 1000,
    category: 'paan,checks,stone',
    unit: 'mm',
    color: 'golden',
    hasWeight: 'TRUE',
  },
];

const addParentCategory = () => {
  const newData = data.map((item) => {
    const parentCategory = 'stone';
    const categories = item.category.split(',');
    delete item.category;
    return { ...item, parentCategory, categories };
  });
  fs.writeFileSync('src/db/scripts/raw-stones.json', JSON.stringify(newData));
};

addParentCategory();
